/*
Navicat MySQL Data Transfer

Source Server         : mysql8
Source Server Version : 80022
Source Host           : localhost:3306
Source Database       : bill-manager

Target Server Type    : MYSQL
Target Server Version : 80022
File Encoding         : 65001

Date: 2021-05-09 21:08:13
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `bill_`
-- ----------------------------
DROP TABLE IF EXISTS `bill_`;
CREATE TABLE `bill_` (
  `id_` bigint NOT NULL AUTO_INCREMENT,
  `title_` varchar(100) DEFAULT NULL,
  `bill_time_` date DEFAULT NULL,
  `type_id_` bigint DEFAULT NULL,
  `price_` double(10,2) DEFAULT NULL,
  `explain_` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id_`),
  KEY `fk_type_bill` (`type_id_`),
  CONSTRAINT `fk_type_bill` FOREIGN KEY (`type_id_`) REFERENCES `bill_type_` (`id_`)
) ENGINE=InnoDB AUTO_INCREMENT=506 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of bill_
-- ----------------------------
INSERT INTO `bill_` VALUES ('1', '交通费123', '2021-05-17', '1', '123.00', '123123');
INSERT INTO `bill_` VALUES ('3', '出差费', '2017-06-28', '2', '33.00', 'c');
INSERT INTO `bill_` VALUES ('4', '奖金', '2017-06-29', '2', '44.00', 'd');
INSERT INTO `bill_` VALUES ('30', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('32', 'r', null, null, null, null);
INSERT INTO `bill_` VALUES ('33', 'w', null, null, null, null);
INSERT INTO `bill_` VALUES ('35', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('36', 'aw', null, null, null, null);
INSERT INTO `bill_` VALUES ('37', 'er', null, null, null, null);
INSERT INTO `bill_` VALUES ('38', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('39', 'df', '2021-05-25', '1', '0.00', '');
INSERT INTO `bill_` VALUES ('40', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('41', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('42', 'wae', null, null, null, null);
INSERT INTO `bill_` VALUES ('44', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('45', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('46', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('47', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('48', 'w', null, null, null, null);
INSERT INTO `bill_` VALUES ('49', 'r', null, null, null, null);
INSERT INTO `bill_` VALUES ('50', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('51', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('52', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('53', 'awse', null, null, null, null);
INSERT INTO `bill_` VALUES ('54', 'r', null, null, null, null);
INSERT INTO `bill_` VALUES ('55', 'qer', null, null, null, null);
INSERT INTO `bill_` VALUES ('56', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('57', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('58', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('59', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('60', 'awse', null, null, null, null);
INSERT INTO `bill_` VALUES ('61', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('62', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('63', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('64', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('65', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('66', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('67', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('68', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('69', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('70', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('71', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('72', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('73', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('74', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('75', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('76', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('77', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('78', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('79', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('80', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('81', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('82', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('83', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('84', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('85', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('86', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('87', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('88', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('89', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('90', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('91', 'awer', null, null, null, null);
INSERT INTO `bill_` VALUES ('93', '采购办公用品', '2019-05-22', '4', '666.00', '采购办公用品');
INSERT INTO `bill_` VALUES ('94', '采购办公用品', '2019-05-22', '4', '666.00', '采购办公用品');
INSERT INTO `bill_` VALUES ('95', '采购办公用品', '2019-05-22', '3', '555.00', '222');
INSERT INTO `bill_` VALUES ('96', '采购办公用品', '2019-05-22', '2', '666.00', '采购办公用品');
INSERT INTO `bill_` VALUES ('97', '采购办公用品', '2019-05-22', '2', '222.00', '1234');
INSERT INTO `bill_` VALUES ('98', '采购办公用品', '2019-12-25', '2', '666.00', '采购办公用品');
INSERT INTO `bill_` VALUES ('100', '采购椅子', '2020-06-17', '2', '200.00', '采购办公用品');
INSERT INTO `bill_` VALUES ('101', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('102', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('103', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('104', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('105', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('106', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('107', 'aw', null, null, null, null);
INSERT INTO `bill_` VALUES ('108', 'r', null, null, null, null);
INSERT INTO `bill_` VALUES ('109', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('110', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('111', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('112', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('113', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('114', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('115', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('116', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('117', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('118', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('119', 'wsd', null, null, null, null);
INSERT INTO `bill_` VALUES ('120', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('121', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('122', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('123', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('124', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('125', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('126', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('127', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('128', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('129', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('130', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('131', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('132', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('133', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('134', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('135', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('136', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('137', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('138', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('139', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('140', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('141', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('142', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('143', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('144', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('145', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('146', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('147', 'awer', null, null, null, null);
INSERT INTO `bill_` VALUES ('148', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('149', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('150', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('151', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('152', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('153', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('154', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('155', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('156', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('157', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('158', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('159', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('160', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('161', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('162', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('163', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('164', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('165', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('166', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('167', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('168', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('169', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('170', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('171', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('172', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('173', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('174', 'wsdr', null, null, null, null);
INSERT INTO `bill_` VALUES ('175', 'wae', null, null, null, null);
INSERT INTO `bill_` VALUES ('176', 's', null, null, null, null);
INSERT INTO `bill_` VALUES ('177', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('178', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('179', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('180', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('181', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('182', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('183', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('184', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('185', 'fa', null, null, null, null);
INSERT INTO `bill_` VALUES ('186', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('187', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('188', 'fa', null, null, null, null);
INSERT INTO `bill_` VALUES ('189', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('190', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('191', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('192', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('193', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('194', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('195', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('196', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('197', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('198', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('199', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('200', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('201', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('202', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('203', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('204', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('205', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('206', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('207', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('208', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('209', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('210', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('211', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('212', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('213', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('214', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('215', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('216', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('217', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('218', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('219', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('220', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('221', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('222', 'fd', null, null, null, null);
INSERT INTO `bill_` VALUES ('223', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('224', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('225', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('226', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('227', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('228', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('229', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('230', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('231', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('232', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('233', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('234', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('235', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('236', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('237', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('238', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('239', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('240', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('241', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('242', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('243', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('244', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('245', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('246', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('247', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('248', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('249', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('250', 'asfd', null, null, null, null);
INSERT INTO `bill_` VALUES ('251', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('252', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('253', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('254', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('255', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('256', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('257', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('258', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('259', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('260', 'fa', null, null, null, null);
INSERT INTO `bill_` VALUES ('261', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('262', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('263', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('264', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('265', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('266', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('267', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('268', 'fas', null, null, null, null);
INSERT INTO `bill_` VALUES ('269', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('270', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('271', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('272', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('273', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('274', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('275', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('276', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('277', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('278', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('279', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('280', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('281', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('282', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('283', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('284', 'fa', null, null, null, null);
INSERT INTO `bill_` VALUES ('285', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('286', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('287', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('288', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('289', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('290', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('291', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('292', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('293', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('294', 'awe', null, null, null, null);
INSERT INTO `bill_` VALUES ('295', 'r', null, null, null, null);
INSERT INTO `bill_` VALUES ('296', 'sd', null, null, null, null);
INSERT INTO `bill_` VALUES ('297', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('298', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('299', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('300', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('301', 'sd', null, null, null, null);
INSERT INTO `bill_` VALUES ('302', 'fa', null, null, null, null);
INSERT INTO `bill_` VALUES ('303', 'sd', null, null, null, null);
INSERT INTO `bill_` VALUES ('304', 'r', null, null, null, null);
INSERT INTO `bill_` VALUES ('305', 'qwae', null, null, null, null);
INSERT INTO `bill_` VALUES ('306', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('307', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('308', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('309', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('310', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('311', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('312', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('313', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('314', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('315', 'fa', null, null, null, null);
INSERT INTO `bill_` VALUES ('316', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('317', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('318', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('319', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('320', 'fas', null, null, null, null);
INSERT INTO `bill_` VALUES ('321', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('322', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('323', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('324', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('325', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('326', 'fa', null, null, null, null);
INSERT INTO `bill_` VALUES ('327', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('328', 'asf', null, null, null, null);
INSERT INTO `bill_` VALUES ('329', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('330', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('331', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('332', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('333', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('334', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('335', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('336', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('337', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('338', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('339', 'fa', null, null, null, null);
INSERT INTO `bill_` VALUES ('340', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('341', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('342', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('343', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('344', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('345', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('346', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('347', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('348', 'fd', null, null, null, null);
INSERT INTO `bill_` VALUES ('349', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('350', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('351', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('352', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('353', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('354', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('355', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('356', 'fa', null, null, null, null);
INSERT INTO `bill_` VALUES ('357', 'sd', null, null, null, null);
INSERT INTO `bill_` VALUES ('358', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('359', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('360', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('361', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('362', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('363', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('364', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('365', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('366', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('367', 'sa', null, null, null, null);
INSERT INTO `bill_` VALUES ('368', 'fdasfd', null, null, null, null);
INSERT INTO `bill_` VALUES ('369', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('370', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('371', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('372', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('373', 'd', null, null, null, null);
INSERT INTO `bill_` VALUES ('374', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('375', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('376', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('377', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('378', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('379', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('380', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('381', 'fa', null, null, null, null);
INSERT INTO `bill_` VALUES ('382', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('383', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('384', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('385', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('386', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('387', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('388', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('389', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('390', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('391', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('392', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('393', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('394', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('395', 'sadf', null, null, null, null);
INSERT INTO `bill_` VALUES ('396', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('397', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('398', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('399', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('400', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('401', 'fd', null, null, null, null);
INSERT INTO `bill_` VALUES ('402', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('403', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('404', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('405', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('406', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('407', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('408', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('409', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('410', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('411', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('412', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('413', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('414', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('415', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('416', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('417', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('418', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('419', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('420', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('421', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('422', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('423', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('424', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('425', 'asfd', null, null, null, null);
INSERT INTO `bill_` VALUES ('426', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('427', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('428', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('429', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('430', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('431', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('432', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('433', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('434', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('435', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('436', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('437', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('438', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('439', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('440', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('441', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('442', 'sad', null, null, null, null);
INSERT INTO `bill_` VALUES ('443', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('444', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('445', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('446', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('447', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('448', 'fa', null, null, null, null);
INSERT INTO `bill_` VALUES ('449', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('450', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('451', 'sadf', null, null, null, null);
INSERT INTO `bill_` VALUES ('452', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('453', 'fa', null, null, null, null);
INSERT INTO `bill_` VALUES ('454', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('455', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('456', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('457', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('458', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('459', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('460', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('461', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('462', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('463', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('464', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('465', 'fas', null, null, null, null);
INSERT INTO `bill_` VALUES ('466', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('467', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('468', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('469', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('470', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('471', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('472', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('473', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('474', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('475', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('476', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('477', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('478', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('479', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('480', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('481', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('482', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('483', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('484', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('485', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('486', 'sdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('487', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('488', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('489', 'sadf', null, null, null, null);
INSERT INTO `bill_` VALUES ('490', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('491', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('492', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('493', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('494', 'a', null, null, null, null);
INSERT INTO `bill_` VALUES ('495', 'df', null, null, null, null);
INSERT INTO `bill_` VALUES ('496', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('497', 'as', null, null, null, null);
INSERT INTO `bill_` VALUES ('498', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('499', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('500', 'asd', null, null, null, null);
INSERT INTO `bill_` VALUES ('501', 'f', null, null, null, null);
INSERT INTO `bill_` VALUES ('502', 'asdf', null, null, null, null);
INSERT INTO `bill_` VALUES ('504', '借给小美4000元', '2020-07-01', '3', '4000.00', '不用还');
INSERT INTO `bill_` VALUES ('505', '钱钱钱', '2021-05-12', '1', '999.00', 'wqe');

-- ----------------------------
-- Table structure for `bill_type_`
-- ----------------------------
DROP TABLE IF EXISTS `bill_type_`;
CREATE TABLE `bill_type_` (
  `id_` bigint NOT NULL AUTO_INCREMENT,
  `name_` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id_`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of bill_type_
-- ----------------------------
INSERT INTO `bill_type_` VALUES ('1', '收入');
INSERT INTO `bill_type_` VALUES ('2', '支出');
INSERT INTO `bill_type_` VALUES ('3', '借入');
INSERT INTO `bill_type_` VALUES ('4', '借出');
