spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bill-manager
    username: root
    password: root
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.gps.entity  #别名
  mapper-locations: classpath:/mybatis/*.xml


